name: Deploy to Staging & Production

on:
  workflow_dispatch:

jobs:
  deploy-stg:
    name: deploy-stg
    runs-on: ubuntu-latest
    environment:
      name: stg
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Deploy CloudFormation
        shell: bash
        run: |
          echo "Deploy to ${{ vars.DEPLOY_ACCOUNT_ALIAS }} account..."

  deploy-prod:
    name: deploy-prod
    runs-on: ubuntu-latest
    needs: [deploy-stg]
    environment:
      name: prod
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Deploy CloudFormation
        shell: bash
        run: |
          echo "Deploy to ${{ vars.DEPLOY_ACCOUNT_ALIAS }} account..."