name: Deploy App to Staging & Production

on:
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: ap-northeast-1

jobs:
  deploy-app-stg:
    name: deploy-app-stg
    runs-on: ubuntu-latest
    environment:
      name: stg
    env:
      ECR_REPOSITORY: ${{ vars.PROJECT_NAME }}-${{ vars.DEPLOY_ACCOUNT_ALIAS }}-ecr-app
    permissions:
      id-token: write
      contents: read
    outputs:
      image_uri: ${{ steps.build-image.outputs.image }}

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Output Image URI
        id: build-image
        run: echo "image=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}" >> $GITHUB_OUTPUT

  deploy-app-prod:
    name: deploy-app-prod
    runs-on: ubuntu-latest
    needs: [deploy-app-stg]
    environment:
      name: prod
    env:
      ECR_REPOSITORY: ${{ vars.PROJECT_NAME }}-${{ vars.DEPLOY_ACCOUNT_ALIAS }}-ecr-app
      SOURCE_IMAGE: ${{ needs.deploy-app-stg.outputs.image_uri }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: "${{ secrets.STG_AWS_ACCOUNT_ID }},${{ secrets.PROD_AWS_ACCOUNT_ID }}"

      - name: Promote Image from Staging to Prod
        run: |
          TARGET_IMAGE="${{ secrets.PROD_AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}"

          echo "Promoting image..."
          echo "Source: $SOURCE_IMAGE"
          echo "Target: $TARGET_IMAGE"

          docker pull $SOURCE_IMAGE
          docker tag $SOURCE_IMAGE $TARGET_IMAGE
          docker push $TARGET_IMAGE
