name: Deploy App to Staging & Production

on:
  workflow_dispatch:

env:
  PROJECT_NAME: build-once

jobs:
  deploy-app-stg:
    name: deploy-app-stg
    runs-on: ubuntu-latest
    environment:
      name: stg
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Build App
        uses: ./.github/actions/build-app

  deploy-app-prod:
    name: deploy-app-prod
    runs-on: ubuntu-latest
    needs: [deploy-app-stg]
    environment:
      name: prod
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Build App
        uses: ./.github/actions/build-app
