name: Deploy App to Staging & Production

on:
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: ap-northeast-1

jobs:
  deploy-app-stg:
    name: deploy-app-stg
    runs-on: ubuntu-latest
    environment:
      name: stg
    env:
      ECR_REPOSITORY: ${{ vars.PROJECT_NAME }}-${{ vars.DEPLOY_ACCOUNT_ALIAS }}-ecr-app
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      # - name: Build App
      #   uses: ./.github/actions/build-app
      #   with:
      #     aws-region: ${{ env.AWS_DEFAULT_REGION }}
      #     aws-account-id: ${{ secrets.AWS_ROLE_ARN }}


  # deploy-app-prod:
  #   name: deploy-app-prod
  #   runs-on: ubuntu-latest
  #   needs: [deploy-app-stg]
  #   environment:
  #     name: prod
  #   permissions:
  #     id-token: write
  #     contents: read

  #   steps:
  #     - name: Checkout this repository
  #       uses: actions/checkout@v4

  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-region: ap-northeast-1
  #         role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

  #     - name: Login to ECR
  #       uses: docker/login-action@v3
  #       with:
  #         registry: <aws-account-number>.dkr.ecr.<region>.amazonaws.com
