name: Deploy Infra to Staging & Production

on:
  workflow_dispatch:

env:
  PROJECT_NAME: build-once

jobs:
  deploy-infra-stg:
    name: deploy-infra-stg
    runs-on: ubuntu-latest
    environment:
      name: stg
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Replace place holder to allow prod deploy role access staging ecr
        env:
          PROD_DEPLOY_ROLE_ARN: ${{ secrets.PROD_DEPLOY_ROLE_ARN }}
        run: |
          envsubst < cfn/params/${{ vars.DEPLOY_ACCOUNT_ALIAS }}/ecr-app.json

      - name: Deploy Infra
        uses: ./.github/actions/deploy-infra
        with:
          environment: ${{ vars.DEPLOY_ACCOUNT_ALIAS }}
          aws-region: ap-northeast-1
          stack-prefix: ${{ env.PROJECT_NAME }}-${{ vars.DEPLOY_ACCOUNT_ALIAS }}

  deploy-infra-prod:
    name: deploy-infra-prod
    runs-on: ubuntu-latest
    needs: [deploy-infra-stg]
    environment:
      name: prod
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Deploy Infra
        uses: ./.github/actions/deploy-infra
        with:
          environment: ${{ vars.DEPLOY_ACCOUNT_ALIAS }}
          aws-region: ap-northeast-1
          stack-prefix: ${{ env.PROJECT_NAME }}-${{ vars.DEPLOY_ACCOUNT_ALIAS }}
